In [1]:
import numpy as np

In [56]:
j=[4,6,2,8,9,1]
j

[4, 6, 2, 8, 9, 1]

In [58]:
np.array(j)

array([4, 6, 2, 8, 9, 1])

In [60]:
tuple(j)

(4, 6, 2, 8, 9, 1)

In [62]:
d=np.array(j)

In [64]:
d

array([4, 6, 2, 8, 9, 1])

In [66]:
d.ndim

1

In [68]:
d.shape

(6,)

In [26]:
d.size

5

In [70]:
h=d.reshape(2,3)
h

array([[4, 6, 2],
       [8, 9, 1]])

In [72]:
import numpy as np

In [74]:
s=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
s

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [76]:
arr1=np.array(s)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
arr1.shape

(4, 4)

In [80]:
arr1.size

16

In [82]:
arr1.ndim

2

In [89]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
z=arr1.reshape(16,1)
z

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [95]:
range(5,20)

range(5, 20)

In [97]:
m=[3,4,5,6,7,8]
m

[3, 4, 5, 6, 7, 8]

In [99]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [107]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [111]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [113]:
range(-1,-10)

range(-1, -10)

In [117]:
for i in range(5,50,5):
 print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [119]:
j=[10,20,30,40,50,60,70,800,90]
j

[10, 20, 30, 40, 50, 60, 70, 800, 90]

In [128]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
         x.append(j[i])
    else:
         y.append(j[i])
         print(x)
         print(y)

[10]
[20]
[10, 30]
[20, 40]
[10, 30, 50]
[20, 40, 60]
[10, 30, 50, 70]
[20, 40, 60, 800]
