In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
k=[4,2.56789,9,87,9999,40,'Hyderabad']
k

[4, 2.56789, 9, 87, 9999, 40, 'Hyderabad']

In [10]:
pd.Series(k)

0            4
1      2.56789
2            9
3           87
4         9999
5           40
6    Hyderabad
dtype: object

In [12]:
k=[4,2.56789,9,87,9999,40]
k

[4, 2.56789, 9, 87, 9999, 40]

In [14]:
pd.Series(k)

0       4.00000
1       2.56789
2       9.00000
3      87.00000
4    9999.00000
5      40.00000
dtype: float64

In [34]:
a=np.random.randint(20,50,15)
a

array([33, 22, 43, 41, 32, 33, 23, 39, 41, 31, 44, 22, 46, 43, 38])

In [36]:
a.ndim

1

In [38]:
pd.Series(a)

0     33
1     22
2     43
3     41
4     32
5     33
6     23
7     39
8     41
9     31
10    44
11    22
12    46
13    43
14    38
dtype: int32

In [40]:
s=pd.Series(a)
s

0     33
1     22
2     43
3     41
4     32
5     33
6     23
7     39
8     41
9     31
10    44
11    22
12    46
13    43
14    38
dtype: int32

In [42]:
s[0]

33

In [44]:
s[4:10]

4    32
5    33
6    23
7    39
8    41
9    31
dtype: int32

In [50]:
b=np.random.randint(100,200,(6,5))
b

array([[132, 190, 104, 174, 158],
       [109, 139, 161, 161, 112],
       [145, 167, 122, 119, 121],
       [128, 128, 169, 152, 168],
       [164, 165, 163, 196, 140],
       [167, 141, 108, 153, 161]])

In [54]:
b.ndim

2

In [57]:
b.shape

(6, 5)

In [59]:
b

array([[132, 190, 104, 174, 158],
       [109, 139, 161, 161, 112],
       [145, 167, 122, 119, 121],
       [128, 128, 169, 152, 168],
       [164, 165, 163, 196, 140],
       [167, 141, 108, 153, 161]])

In [63]:
df=pd.DataFrame(b)
df

0    1    2    3    4
0  132  190  104  174  158
1  109  139  161  161  112
2  145  167  122  119  121
3  128  128  169  152  168
4  164  165  163  196  140
5  167  141  108  153  161

In [65]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'])
df

Roll  name  age  adds  country
0   132   190  104   174      158
1   109   139  161   161      112
2   145   167  122   119      121
3   128   128  169   152      168
4   164   165  163   196      140
5   167   141  108   153      161

In [67]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'],index=[182,183,185,186,187,188])
df


Roll  name  age  adds  country
182   132   190  104   174      158
183   109   139  161   161      112
185   145   167  122   119      121
186   128   128  169   152      168
187   164   165  163   196      140
188   167   141  108   153      161

In [75]:
df.iloc[0]#given defaults values

Roll       132
name       190
age        104
adds       174
country    158
Name: 182, dtype: int32

In [77]:
df.loc[182]

Roll       132
name       190
age        104
adds       174
country    158
Name: 182, dtype: int32

In [79]:
df.iloc[0,0]

132

In [81]:
df.loc[182,'Roll']

132

In [85]:
df.loc[182,['Roll','name','age']]

Roll    132
name    190
age     104
Name: 182, dtype: int32

In [87]:
df.iloc[0,0:3]

Roll    132
name    190
age     104
Name: 182, dtype: int32

In [89]:
df.iloc[0,[0,1,2]]

Roll    132
name    190
age     104
Name: 182, dtype: int32

In [91]:
df.iloc[[0,5]]


Roll  name  age  adds  country
182   132   190  104   174      158
188   167   141  108   153      161

In [93]:
df.iloc[[1,3,4]]

Roll  name  age  adds  country
183   109   139  161   161      112
186   128   128  169   152      168
187   164   165  163   196      140

In [95]:
df.loc[[182,186,187]]

Roll  name  age  adds  country
182   132   190  104   174      158
186   128   128  169   152      168
187   164   165  163   196      140

In [97]:
df

Roll  name  age  adds  country
182   132   190  104   174      158
183   109   139  161   161      112
185   145   167  122   119      121
186   128   128  169   152      168
187   164   165  163   196      140
188   167   141  108   153      161

In [99]:
df.age

182    104
183    161
185    122
186    169
187    163
188    108
Name: age, dtype: int32

In [101]:
df['age']

182    104
183    161
185    122
186    169
187    163
188    108
Name: age, dtype: int32

In [115]:
df[['age','adds','Roll',]]

age  adds  Roll
182  104   174   132
183  161   161   109
185  122   119   145
186  169   152   128
187  163   196   164
188  108   153   167