In [3]:
import pandas as np
import numpy as np

In [14]:
a=np.random.randint(20,60,15)

In [16]:
a

array([42, 47, 41, 26, 57, 43, 30, 30, 58, 42, 50, 47, 25, 28, 22])

In [18]:
a.ndim

1

In [20]:
a[12]

25

In [22]:
a

array([42, 47, 41, 26, 57, 43, 30, 30, 58, 42, 50, 47, 25, 28, 22])

In [24]:
30,58,42,50,47,25,28

(30, 58, 42, 50, 47, 25, 28)

In [26]:
a[-2:-10:-1]

array([28, 25, 47, 50, 42, 58, 30, 30])

In [44]:
np.random.seed(94)
b=np.random.randint(15,50,(7,8))
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [46]:
b[2]

array([30, 41, 26, 21, 28, 29, 17, 38])

In [48]:
b[-1]

array([30, 37, 37, 17, 45, 24, 44, 39])

In [50]:
b[:,7]

array([23, 18, 38, 35, 35, 47, 39])

In [52]:
b[:,3]

array([37, 25, 21, 15, 34, 45, 17])

In [54]:
b[3,1]

47

In [56]:
b[5,6]

23

In [58]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [62]:
b[1:5,1:5]

array([[29, 48, 25, 47],
       [41, 26, 21, 28],
       [47, 16, 15, 48],
       [30, 25, 34, 42]])

In [72]:
#array [row_start : row-end : row-step ,col_start : col_end : col_step]

In [70]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [78]:
b[3:7,2:7]

array([[16, 15, 48, 22, 44],
       [25, 34, 42, 16, 39],
       [21, 45, 37, 48, 23],
       [37, 17, 45, 24, 44]])

In [80]:
b[1:7,1:7]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [82]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [126]:
b[2:5:2,1:8:3]

array([[41, 28, 38],
       [30, 42, 35]])

In [129]:
np.where(b>30)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 6, 6, 6, 6, 6], dtype=int64),
 array([0, 3, 4, 5, 6, 0, 2, 4, 5, 6, 1, 7, 0, 1, 4, 6, 7, 3, 4, 6, 7, 0,
        1, 3, 4, 5, 7, 1, 2, 4, 6, 7], dtype=int64))