In [1]:
stud_2nd=[18,19,20,20,20,19,18,18,18,20,20]

In [3]:
import numpy as np
np.random.randint(18,21,(300))

array([20, 18, 20, 18, 18, 19, 19, 18, 19, 18, 20, 18, 18, 19, 18, 19, 18,
       19, 20, 20, 20, 19, 19, 18, 20, 18, 19, 19, 20, 18, 18, 19, 18, 20,
       19, 19, 19, 18, 20, 19, 18, 19, 20, 20, 19, 19, 18, 19, 18, 20, 18,
       18, 20, 18, 18, 20, 20, 19, 20, 18, 19, 19, 18, 19, 19, 18, 20, 20,
       18, 20, 18, 18, 19, 19, 18, 18, 18, 19, 18, 18, 20, 18, 20, 19, 20,
       18, 20, 18, 19, 18, 19, 19, 18, 18, 19, 19, 20, 19, 20, 19, 20, 20,
       20, 19, 18, 20, 18, 18, 19, 20, 19, 20, 19, 19, 20, 18, 18, 19, 19,
       20, 20, 18, 20, 18, 19, 18, 18, 20, 18, 18, 18, 18, 19, 19, 20, 18,
       19, 20, 18, 20, 18, 19, 18, 20, 20, 20, 20, 18, 20, 19, 20, 18, 18,
       18, 18, 20, 18, 18, 19, 18, 19, 19, 20, 18, 19, 18, 19, 20, 18, 20,
       19, 18, 19, 19, 20, 18, 20, 20, 20, 19, 19, 20, 20, 20, 20, 18, 18,
       20, 20, 18, 18, 18, 19, 19, 20, 19, 20, 20, 19, 19, 18, 19, 19, 19,
       20, 18, 19, 18, 20, 20, 18, 20, 18, 20, 18, 19, 19, 19, 19, 19, 20,
       19, 18, 20, 19, 20

In [5]:
import numpy as np
tenth_std=np.random.randint(15,18,(1000))
tenth_std+0.3

array([17.3, 17.3, 17.3, 17.3, 17.3, 15.3, 17.3, 15.3, 17.3, 16.3, 16.3,
       17.3, 15.3, 15.3, 15.3, 17.3, 15.3, 15.3, 16.3, 15.3, 17.3, 15.3,
       15.3, 17.3, 15.3, 16.3, 17.3, 16.3, 17.3, 17.3, 16.3, 17.3, 17.3,
       17.3, 15.3, 16.3, 17.3, 16.3, 15.3, 15.3, 16.3, 17.3, 16.3, 16.3,
       17.3, 17.3, 17.3, 17.3, 16.3, 16.3, 17.3, 15.3, 16.3, 17.3, 15.3,
       16.3, 17.3, 17.3, 15.3, 16.3, 15.3, 16.3, 17.3, 15.3, 15.3, 17.3,
       17.3, 16.3, 17.3, 17.3, 17.3, 15.3, 16.3, 17.3, 17.3, 16.3, 16.3,
       17.3, 16.3, 15.3, 15.3, 15.3, 15.3, 16.3, 15.3, 15.3, 16.3, 16.3,
       17.3, 15.3, 17.3, 17.3, 16.3, 17.3, 16.3, 16.3, 17.3, 15.3, 17.3,
       16.3, 17.3, 15.3, 17.3, 16.3, 15.3, 17.3, 16.3, 17.3, 16.3, 15.3,
       16.3, 17.3, 17.3, 16.3, 15.3, 15.3, 15.3, 15.3, 16.3, 16.3, 17.3,
       15.3, 15.3, 17.3, 16.3, 15.3, 17.3, 15.3, 15.3, 17.3, 15.3, 15.3,
       16.3, 17.3, 17.3, 15.3, 15.3, 17.3, 15.3, 17.3, 16.3, 15.3, 15.3,
       17.3, 17.3, 15.3, 16.3, 15.3, 15.3, 17.3, 15

In [7]:
import numpy as np

In [9]:
np.random.seed(234)
arr=np.random.randint(20,99,(6,7))

In [11]:
arr

array([[92, 51, 88, 77, 53, 23, 74],
       [83, 87, 54, 74, 28, 59, 91],
       [52, 79, 84, 46, 91, 43, 23],
       [35, 65, 65, 23, 97, 93, 71],
       [39, 40, 43, 38, 27, 35, 61],
       [23, 93, 60, 93, 75, 43, 98]])

In [13]:
arr.size

42

In [19]:
m=[5,20,10,6,8]
m

[5, 20, 10, 6, 8]

In [21]:
numbers=[5,20,10,6,8]
square_numbers = [x**2 for x in m]
print("Squared list:",square_numbers)

Squared list: [25, 400, 100, 36, 64]


In [27]:
b=[3,6,7,8,9]
b

[3, 6, 7, 8, 9]

In [31]:
b=tuple(x+5 for x in b)
b

(8, 11, 12, 13, 14)

In [33]:
k=[55,25,85,75,35,45,95]
k

[55, 25, 85, 75, 35, 45, 95]

In [35]:
k=[x for x in k if x>50]
k

[55, 85, 75, 95]

In [41]:
np.random.seed(5)
arr=np.random.randint(20,90,10)

In [43]:
arr

array([81, 36, 28, 82, 47, 50, 27, 35, 73, 47])

In [45]:
arr+5

array([86, 41, 33, 87, 52, 55, 32, 40, 78, 52])

In [47]:
arr**2

array([6561, 1296,  784, 6724, 2209, 2500,  729, 1225, 5329, 2209])